# Setup
title:               The Academy
tagline:             'Read Platonic Dialgoues'
description:         'A place to read Platonic dialogues and other works from Platos Academy.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty
github:              https://github.com/insomnicles/academy

# About/contact
author:
  name:              Plato
  url:               https://twitter.com/mdo
  email:             plato@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
