# Setup
title:               The Academy
tagline:             'Read Platonic Dialgoues'
description:         'A place to read works of philosophy and drama from antiquity.'
url:                 https://insomnicles.github.io/academy
baseurl:             ''
paginate:            5
permalink:           pretty
github:              https://github.com/insomnicles/academy

# About/contact
author:
  name:              Plato
  url:               https://twitter.com
  email:             plato@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
